# Created by Jekyll Writer
title: Air Blog
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: "https://air-s.github.io/blog/"
baseurl: ""
lsi: false
safe: true
auto: false
timezone: Asia/Shanghai
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

author: Air
description: ''
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: QIUPENMING
github_username: Air-s
gems:
  - jekyll-paginate
baseurl: /blog
