# Created by Jekyll Writer
title: Air Blog
author: Air
description: ''
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: QIUPENMING
github_username: Air-s
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /blog

theme: jekyll-theme-slate