# Created by Jekyll Writer
title: Air Blog
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
highlights: pygments
timezone: Asia/Shanghai
author: Air
description: ''
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: QIUPENMING
github_username: Air-s
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
baseurl: /blog
